# Generated by Django 6.0.5 on 2026-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_content_type_user_avatar_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_storage_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
