sonar.projectKey=HuynhhBao_KCPM
sonar.organization=huynhhbao

sonar.sources=backend,mobile/lib

sonar.exclusions=backend/**/migrations/**,backend/**/tests.py,backend/unit_tests/**,mobile/lib/**/*.g.dart,mobile/lib/**/*.freezed.dart,mobile/test/**

sonar.tests=backend/unit_tests,mobile/test
sonar.test.inclusions=backend/unit_tests/**,mobile/test/**

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info
