# Generated by Django 6.0.5 on 2026-05-29 08:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
    ]
