# Generated by Django 6.0.5 on 2026-05-29 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_debt_paid_amount'),
        ('households', '0007_alter_household_invite_code'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_pending_payment_per_debt',
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.debt'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('debt__isnull', False)), fields=('debt',), name='unique_pending_payment_per_debt'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('household', 'payer', 'receiver'), name='unique_pending_payment_per_pair'),
        ),
    ]
