# Generated by Django 6.0.5 on 2026-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_unique_pending_payment_per_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_pair_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_after_confirm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
