# Generated by Django 6.0.5 on 2026-06-07 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_expense_date'),
        ('payments', '0003_payment_is_pair_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('full', 'Thanh toán toàn bộ'), ('selected_items', 'Chọn khoản thanh toán'), ('custom_amount', 'Thanh toán trước một khoản')], db_index=True, default='custom_amount', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='expenses.debt')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'debt'), name='unique_payment_allocation_per_debt')],
            },
        ),
    ]
